##################################################
#     Economies - Plugin Configuration File      #
##################################################

# Sets various balance options for bank accounts:
balance:

  # Sets the initial balance for a bank account: (Type: Long, Default: 1000)
  # Note: Must be greater than or equal to zero, otherwise the default value will be used.
  initial: 1000

  # Sets whether overdrafts/loans are enabled: (Type: Boolean, Default: true)
  # Note: Player must have the permission (economies.creditworthy) to overdraft their account.
  overdrafts: true

# Sets various options for the bank:
bank:

  # Sets the global balance for the bank: (Type: Long, Default: 1000000000)
  # Note: Must be greater than zero, otherwise the default value will be used.
  global: 1000000000

  # Sets whether the balance of the bank is infinite: (Type: Boolean, Default: true)
  # Note: When disabled, the money in circulation will always be the amount specified by 'bank.global'.
  infinite: true

  # Sets the name of the global bank account: (Type: String, Default: "Bank")
  name: "Bank"

# Sets whether the plugin should log debug information's to the console: (Type: Boolean, Default: false)
debug: false